apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hl7-v2-connector.name" . }}
  labels:
    {{- include "hl7-v2-connector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hl7-v2-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "hl7-v2-connector.labels" . | nindent 8 }}
    spec:
      containers:
        - name: hl7-v2-connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: config-volume
              mountPath: /config
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: { { .Values.service.port } }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: { { .Values.service.port } }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.config.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "hl7-v2-connector.name" . }}-config
        {{- end }}