image:
  repository: ghcr.io/lilianasacorreia/hl7-v2-connector
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2575

resources: {}

env:
   - name: KAFKA_BOOTSTRAP_SERVERS
     value: "redpanda:9092"
   - name: FHIR_TRANSACTION_INBOUND_TOPIC
     value: "inbound-fhir-transactions"
   - name: REQUEST_IN_V2_TOPIC
     value: "hl7v2-request-in-message"
   - name: TCP_LOCALHOST
     value: "0.0.0.0"
   - name: TCP_PORT
     value: "2575"

config:
  enabled: false
  data: {}
  # Exemplo:
  # data:
  #   connector.properties: |
  #     hl7.port=2575
  #     hl7.charset=UTF-8

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []