image:
  repository: your-registry/hl7-v2-connector
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081   # ajusta se o teu conector usar outra porta

resources: {}

env: []
# Exemplo:
# env:
#   - name: KAFKA_BOOTSTRAP
#     value: redpanda:9092

config:
  enabled: false
  data: {}
  # Exemplo:
  # data:
  #   connector.properties: |
  #     hl7.port=2575
  #     hl7.charset=UTF-8

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []